### ISSUE TITLE
UpdatePackageCriticalFileNotFoundException

### ISSUE THREAD

**Issue by tksh164** [tksh164/updb.dnc#17]
```
D:\Temp\updb-sample>dir /s /b *.msu | "J:\updb.dnc\src\updbcmd\bin\Debug\netcoreapp3.1\updbcmd.exe"
Unhandled exception. UPDB.Gathering.MscfUpdatePackageDataRetrieveException: Could not retrieve the data from update package "D:\Temp\updb-sample\04.Apr_2020\07.2019\windows10.0-kb4538461-x64.msu".
 ---> UPDB.Gathering.UpdatePackageCriticalFileNotFoundException: The critical file "C:\Users\takatano\AppData\Local\Temp\l0b\*-pkgProperties.txt" did not exist in the update package file.
   at UPDB.Gathering.UpdatePackage.GetFilePathDirectlyUnderFolder(String workFolderPath, String fileNamePattern) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackage.cs:line 194
   at UPDB.Gathering.UpdatePackage.RetrieveData(String updatePackageFilePath) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackage.cs:line 54
   --- End of inner exception stack trace ---
   at UPDB.Gathering.UpdatePackage.RetrieveData(String updatePackageFilePath) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackage.cs:line 74
   at updbcmd.Program.Main(String[] args) in J:\updb.dnc\src\updbcmd\Program.cs:line 16
```

**Comment by tksh164** [comment]
The windows10.0-kb4538461-x64.msu had the following files:
- Windows10.0-KB4538461-x64_PSFX.cab
- Windows10.0-KB4538461-x64_PSFX.xml
- Windows10.0-KB4538461-x64-pkgProperties_PSFX.txt

The "_PSFX" suffix is not general. It is a special case.
