### ISSUE TITLE
UpdatePackageXmlAttributeNotFoundException

### ISSUE THREAD

**Issue by tksh164** [tksh164/updb.dnc#9]
```
D:\Temp\updb-sample>dir /s /b *.msu | "J:\updb.dnc\src\updbcmd\bin\Debug\netcoreapp3.1\updbcmd.exe"
Unhandled exception. UPDB.Gathering.MscfUpdatePackageDataRetrieveException: Could not retrieve the data from update package "D:\Temp\updb-sample\04.Apr_2020\01.2012\ie11-windows6.2-kb4540671-x64.msu".
 ---> UPDB.Gathering.UpdatePackageXmlAttributeNotFoundException: The "selfUpdate" attribute did not found on the "/u:assembly/u:package" node.
   at UPDB.Gathering.UpdatePackageXmlDocument.GetXmlAttributeValue(String nodeXPath, String attributeName) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackageXmlDocument.cs:line 27
   at UPDB.Gathering.UpdatePackageMetadataFromUpdateMumFile..ctor(String updateMumFilePath) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackageMetadataFromUpdateMumFile.cs:line 49
   at UPDB.Gathering.UpdatePackage.RetrieveData(String updatePackageFilePath) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackage.cs:line 62
   --- End of inner exception stack trace ---
   at UPDB.Gathering.UpdatePackage.RetrieveData(String updatePackageFilePath) in J:\updb.dnc\src\updblib\Gathering\UpdatePackage\UpdatePackage.cs:line 74
   at updbcmd.Program.Main(String[] args) in J:\updb.dnc\src\updbcmd\Program.cs:line 15
```

**Comment by tksh164** [comment]
The selfUpdate and permanence were not required attributes of the /ssembly/package element.
